- name: Create file systems
  filesystem:
    fstype: "{{ fs.fstype | default(default_fstype) }}"
    dev: "{{ fs.device }}"
    opts: "{{ fs.mkfs_opts | default(default_mkfs_opts) }}"
    force: "{{ fs.force | default(default_force | bool) }}"
  with_items: "{{ filesystems }}"
  loop_control:
    loop_var: fs
  when: filesystems is defined

- name: Mount file systems
  mount:
    path: "{{ mount.mountpoint }}"
    src: "{{ mount.device }}"
    fstype: "{{ mount.fstype | default(default_fstype) }}"
#    opts: "{{ mount.mount_opts | default(default_mount_opts) }}"
    state: "{{ mount.state | default(default_state) }}"
  with_items: "{{ filesystems }}"
  loop_control:
    loop_var: mount
  when: filesystems is defined

